### ISSUE TITLE
Potential issue with conflicting accounts name

### ISSUE THREAD

**Issue by alagroy-42** [jelix/authentication-module#4]
Once multiples identity providers will be implemented, I'm affraid there will be problems with the `account` module if some users choose the same username with different identity providers (The module has been built to identify accounts by their name which means they have to be unique).

Is there a way for the `account` module to deny authentication from some users while they have the same name than an already registered user using a  different identity provider so they can change instead of denying them an account ?

If no, what should we change to avoid this issue ?
I can think of changing the way accounts are stored or implementing a way to deny the user creation. The second solution seems simpler to implement.

**Comment by laurentj** [comment]
Fixed, with a new internal design.
